In [ ]:
import numpy as np
import scipy.linalg as la

### Basic aspects of numpy matrices

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
print("A = ", A)
print("Dimensions: ", A.ndim) # number of dimensions
print("Shape: ", A.shape) # shape returned as a tuple
print("Size: ", A.size) # total number of entries in the array

A =  [[1 2]
 [3 4]
 [5 6]]
Dimensions:  2
Shape:  (3, 2)
Size:  6


When slicing a numpy matrix, the result is a 1-dimensional array. This is not a vector; to select a vector, we use reshape:

In [ ]:
col1 = A[:,0]
print(col1)

[1 3 5]


In [ ]:
col_vec = col1.reshape(3)
print(col_vec)

[1 3 5]


In [ ]:
col_vec = col1.reshape(3, 1)
print(col_vec)

[[1]
 [3]
 [5]]


In [ ]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [ ]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
D = np.diag([1, 2, 3, 4])
I4 = np.eye(4)

print("D * I4 = ", D@I4)

D * I4 =  [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [ ]:
D1 = np.diag([1.1, 2.2, 3.3, 4.4])

print(D1@I4)

[[1.1 0.  0.  0. ]
 [0.  2.2 0.  0. ]
 [0.  0.  3.3 0. ]
 [0.  0.  0.  4.4]]


In [ ]:
from numpy.linalg import matrix_power as mpow

print(D@D)
print(mpow(D, 2))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [ ]:
print(D)
print(D.T)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
print(I4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x = np.array([[1, 3, 5]])
y = np.array([[2, 4, 6]])

print(x)
print(y.T)
print(np.dot(x, y.T))
print(np.vdot(x, y))
print(np.outer(x, y))

[[1 3 5]]
[[2]
 [4]
 [6]]
[[44]]
44
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [ ]:
print(x)
print(x.reshape((1, 3))) # row vector x
print(x.reshape((3, 1))) # column vector x
print(x.T) # equivalent to taking its transpose

[1 3 5]
[[1 3 5]]
[[1]
 [3]
 [5]]
[1 3 5]


In [ ]:
import numpy.linalg as la2
import math
print(np.trace(D))
print(la2.norm(D)) # calculates the norm
print(la2.norm(x, 1))
print(la.norm(x, 1))

10
5.477225575051661
5.0
5.0
