# Linear algebra in Python
## I'm playing around with numpy and scipy to better understand what the equivalents for concepts I learned offline are in Python.

In [8]:
import numpy as np
import scipy.linalg as la

In [4]:
a = np.array([1, 3, 2, -1])
print(a)

[ 1  3  2 -1]


In [5]:
a.ndim # this is the number of dimensions

1

In [6]:
a.shape # this is the shape——a Python tuple

(4,)

In [9]:
a.size # and this is the total number of entries in the array

4

In [11]:
M = np.array([[1, 2], [3, 7], [-1, 5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [13]:
M.ndim

2

In [15]:
M.shape

(3, 2)

In [20]:
col1 = M[:, 0]
col2 = M[:, 1]
print(col1)
print(col2)

[ 1  3 -1]
[2 7 5]


The above selects the column as a 1D numpy array, but we might want to select it asa 2D column vector. (why?)

In [25]:
print('Dimensions:', col.ndim)
print('Shape: ', col.shape)
print('Size: ', col.size)

Dimensions: 1
Shape:  (3,)
Size:  3


In [24]:
column = np.array([2, 7, 5]).reshape(3, 1)
print('Dimensions:', column.ndim)
print('Shape: ', column.shape)
print('Size: ', column.size)

Dimensions: 2
Shape:  (3, 1)
Size:  3


### Matrix operations and functions

In [26]:
M = np.array([[3, 4], [-1, 5]])
print(M)
print(M*M)

[[ 3  4]
 [-1  5]]
[[ 9 16]
 [ 1 25]]


We use the "@" sign for actual matrix multiplication, because other operators are applied element-wise.


In [27]:
M@M

array([[ 5, 32],
       [-8, 21]])

In [29]:
N = np.array([[3, 4]])

In [31]:
A = np.array([[1, 3], [-1, 7]])
B = np.array([[5, 2], [1, 2]])
I = np.eye(2)

print(2*I + 3*A - A@B)

[[-3.  1.]
 [-5. 11.]]


In [33]:
from numpy.linalg import matrix_power as mpow

In [34]:
M

array([[ 3,  4],
       [-1,  5]])

In [35]:
print(M@M)
print(mpow(M, 2))

[[ 5 32]
 [-8 21]]
[[ 5 32]
 [-8 21]]


In [36]:
print(M)

[[ 3  4]
 [-1  5]]


In [37]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


In [38]:
M@M.T

array([[25, 17],
       [17, 26]])

In [39]:
M.T@M

array([[10,  7],
       [ 7, 41]])

In [40]:
(M@M.T).T

array([[25, 17],
       [17, 26]])

In [41]:
la.inv(A)

array([[ 0.7, -0.3],
       [ 0.1,  0.1]])

In [42]:
np.trace(M)

8

In [44]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
B = (np.arange(9)-4).reshape((3, 3))

In [46]:
print(B)

[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]


In [47]:
print(la.norm(B, 2))

7.3484692283495345


In [48]:
la.norm(B)

7.745966692414834

In [49]:
print(la.det(A))

10.0


In [50]:
A

array([[ 1,  3],
       [-1,  7]])

In [51]:
np.zeros(3)

array([0., 0., 0.])